//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameDefaultConnection : DbContext
    {
        public GameDefaultConnection()
            : base("name=GameDefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game1> Games { get; set; }
        public virtual DbSet<GameScore1> GameScores { get; set; }
        public virtual DbSet<Team1> Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
