//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game1
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public string Description { get; set; }
        public int TotalScore { get; set; }
        public long Spectators { get; set; }
        public string WinningTeam { get; set; }
    }
}
